### ISSUE TITLE
Use third party for email notifications

### ISSUE THREAD

**Issue by katyok** [JojoAdventure/liftoff-assignments#1]
Relevant thread from the slack channel below. I'm going to steer you away from email automation being the most advanced part of your application. The amount of things you can show off for the time spent is not worth it. Plus, it looks like email automation can be done in Spring itself (see the link below).

dave [3:15 PM]
I'm grading a bunch of assignments, and a lot of them list email notification as a feature. Forgive my ignorance of the newfangled webhosts these days, but isn't that too hard to actually deploy for a student project? I recall it being pretty pesky - ~10 hours of webhost configuration and non-programming doc reading, and at the end all I had was the ability to send email. That seems like an awful lot of work for something that won't exactly wow employers.

ryuhhnn [3:19 PM]
I would guide them towards using an email API if you have reservations @dave Amazon AWS offers Simple Email Service that can send up to 1M emails for free and it works with every programming languages. There are also services like Sendgrid and Mailgun that offer free tiers with the same support

Doc [3:23 PM]
I'd definitely recommend using a 3rd party email service to cut down the complexity (and more importantly, send emails 'the right way'). Folks wishing to run their own email service should be aware that it will take some technical know-how of configuring your service to your smtp host, and that it likely won't be "production grade", but I think is still doable.

Here's a quick Spring tutorial on sending email: http://www.baeldung.com/spring-email

**Comment by JojoAdventure** [comment]
Thanks a bunch. I know this was mentioned in the last class but it definitely bears repeating. I've used some third party email services in the past but not yet in this context.
Also thank goodness for Spring. Hoo boy.
