### ISSUE TITLE
Elaborate on Technologies

### ISSUE THREAD

**Issue by katyok** [JojoAdventure/liftoff-assignments#2]
There is a ton of opportunity here. A quick search showed me a few different strong APIs that could make your app really powerful, for instance this one that autocompletes searches- https://developer.musicgraph.com/api-docs/v2/tracks and this one that provides suggestions for similar music - https://www.programmableweb.com/api/openstrands. Pick your APIs carefully and study the data source/structure. You will need to understand it to best leverage it for your project. List the APIs that you find suitable. Also get a "full stack" list together. Here's an example for Spring, though you do not necessarily have to use this:

• Spring Boot

• Spring MVC

• MySQL

• Spring Data JPA or Hibernate (There's a difference, but probably a moot point)

• Thymeleaf

**Comment by JojoAdventure** [comment]
Thanks a bunch! I looked into these and they look perfect for my project. Seems like they'll definitely cut down on the overall amount of time the project will take while also adding better functionality and teaching me something new!

**Comment by JojoAdventure** [comment]
To be honest I hadn't considered using APIs when deciding on this project. I'll definitely look into including a few more if necessary.
